export const enum COMMAND_LEVELS {
	SIMPLE = "SIMPLE",
	COMPLEX = "COMPLEX",
	COMBINED = "COMBINED",
}

export const enum COMMAND_SIMPLE {
	WIDTH_LINE = "WIDTH_LINE",
	POINT_LINE = "POINT_LINE",
	EXTEND_LINE = "EXTEND_LINE",
	ARC = "ARC",
	CIRCLE = "CIRCLE",
}

export const enum COMMAND_COMPLEX {
	TRIANGLE = "TRIANGLE",
	PERPENDICULAR_BISECTOR = "PERPENDICULAR_BISECTOR",
	ANGULAR_BISECTOR = "ANGULAR_BISECTOR",
	SIXTY_DEGREE_ANGLE = "SIXTY_DEGREE_ANGLE",
	PERPENDICULAR_LINE_POINT = "PERPENDICULAR_LINE_POINT",
	PERPENDICULAR_EXTERNAL_POINT = "PERPENDICULAR_EXTERNAL_POINT",
}

export const enum COMMAND_COMBINED {
	SEMI_CIRCLE = "SEMI_CIRCLE",
	PERPENDICULAR_LINE_EDGE = "PERPENDULAR_LINE_EDGE",
	CIRCUMSCRIBED_CIRCLE = "CIRCUMSCRIBED_CIRCLE",
	INSCRIBED_CIRCLE = "INSCRIBED_CIRCLE",
	EX_CIRCLE = "EX_CIRCLE",
	TANGENT_CIRCLE_POINT = "TANGENT_CIRCLE_POINT",
	TANGENT_EXTERNAL_POINT = "TANGENT_EXTERNAL_POINT",
}
